spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qtouch?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 991718
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  session:
    timeout: 3600


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ranjun1999.personalutils.model
server:
  port: 8080

mqtt:
  username: root
  password: 991718
  host: tcp://localhost:1883 # 服务器连接地址
  clientID: springClient    # 连接服务器默认客户端ID
  default-topic: home/garden/fountain   # 默认的消息推送主题，实际可在调用接口时指定
  timeout: 100
  keepalive: 100